{
  config,
  pkgs,
  lib,
  ...
}:

let
  # Re-apply "lid closed + external HDMI" layout after Hyprland restarts or config reload.
  # Static `monitor = eDP-1,...` always re-enables the panel; runtime `keyword monitor disable` is lost.
  # Lid bindl only fires on transitions, not when the session already started with the lid closed.
  hyprClosedLidLayout = pkgs.writeShellScript "hypr-closed-lid-layout" ''
    skip_lid_check=false
    [ "''${1:-}" = --force ] && skip_lid_check=true

    if [ "$skip_lid_check" != true ]; then
      lid_closed=false
      for f in /proc/acpi/button/lid/*/state; do
        [ -r "$f" ] || continue
        if grep -qi closed "$f"; then
          lid_closed=true
          break
        fi
      done
      [ "$lid_closed" = true ] || exit 0
    fi

    if ! hyprctl monitors -j 2>/dev/null | grep -q HDMI-A-1; then
      exit 0
    fi
    for i in 1 2 3 4 5; do
      hyprctl dispatch moveworkspacetomonitor "$i" HDMI-A-1
    done
    hyprctl keyword monitor "eDP-1,disable"
    hyprctl dispatch focusmonitor HDMI-A-1
  '';
in
{
  wayland.windowManager.hyprland = {
    enable = true;
    extraConfig = ''
      # Disable experimental Fontations font backend (NixOS 26.05 default) — causes
      # white/blank glyph squares in GTK/Qt popup dialogs and portal windows.
      env = FC_FONTATIONS,0

      # Dark mode + theming for all apps
      env = GTK_THEME,Breeze-Dark

      # Runtime accent color (managed by accent-sync, regenerated on every change)
      source = ~/.config/accent/hyprland.conf

      misc {
        disable_hyprland_logo = true
        disable_splash_rendering = true
      }
      # Volume / brightness (wpctl / brightnessctl)
      bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%+
      bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-
      bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
      bindel = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
      bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
      bind = $mod SHIFT, V, togglefloating
      bind = $mod SHIFT, M, exit
    '';
    settings = {
      "$mod" = "SUPER";

      # French keyboard + mouse sans accélération (plus fluide, 1:1)
      input = {
        kb_layout = "fr";
        kb_variant = "";
        accel_profile = "flat";
        force_no_accel = true;
      };

      cursor = {
        no_hardware_cursors = 1;
      };

      general = {
        gaps_in = 8;
        gaps_out = 12;
        # active_border color is sourced from ~/.config/accent/hyprland.conf
        # (regenerated by accent-sync; defaults to base0D from palette.nix).
        "col.inactive_border" = "rgba(44444433)";
      };

      # Minimal decoration (lightweight, works well on any GPU)
      decoration = {
        rounding = 2;
        active_opacity = 0.75;
        inactive_opacity = 0.60;
      };

      # Special workspace apparaît depuis le bas
      animation = [
        "specialWorkspaceIn, 1, 8, default, slidevert bottom"
        "specialWorkspaceOut, 1, 8, default, slidevert bottom"
      ];

      # Monitors: DP-3 (top, flipped 180°) above HDMI-A-1 (bottom, centered)
      # On zola: DP-3 rule ignored, eDP-1 + HDMI-A-1 fallback
      monitor = [
        "DP-3,2560x1440@75,0x0,1.60,transform,2"
        "HDMI-A-1,1920x1080@60,49x900,1.25"
        "eDP-1,preferred,auto-left,1.25"
        ",preferred,auto,1.25"
      ];

      # Runs on every config reload (e.g. home-manager switch); complements exec-once for cold start.
      exec = [
        "${hyprClosedLidLayout}"
      ];

      # Autostart: Dark mode for portal/Chromium, then bar and wallpaper
      exec-once = [
        "gsettings set org.gnome.desktop.interface gtk-theme Breeze-Dark"
        "gsettings set org.gnome.desktop.interface color-scheme prefer-dark"

        # Closed lid + HDMI: static monitor rules re-enable eDP after restart/rebuild before this ran.
        "${hyprClosedLidLayout}"

        # Apply saved accent color to Hyprland borders + regen all derived configs.
        "accent-sync \"$(cat $HOME/.config/accent/accent.hex 2>/dev/null || echo '#4a4a8e')\""

        # Quickshell (headless - no visible interface)
        "quickshell"

        # Walker launcher daemon (instant startup)
        "walker --gapplication-service"

        # awww wallpaper daemon and initialization
        "awww-daemon"
        "awww-init"
      ];

      # Workspaces: HDMI-A-1 gets ws 1–5, DP-3 gets named workspace "0" (Super+²).
      workspace = [
        "1, monitor:HDMI-A-1, default:true"
        "2, monitor:HDMI-A-1"
        "3, monitor:HDMI-A-1"
        "4, monitor:HDMI-A-1"
        "5, monitor:HDMI-A-1"
        "9, monitor:DP-3, default:true"
        "special:gemini, on-created-empty:hypr-gemini-launch, gapsout:40 100 40 100, gapsin:10"
      ];

      # Minimal binds - terminal, apps
      bind = [
        "$mod, Return, exec, wezterm"
        "$mod, C, exec, code"
        "$mod, D, exec, vesktop"
        "$mod, Z, exec, zen-twilight"
        "$mod, R, exec, walker"
        "$mod, Q, killactive"
        "$mod, T, togglefloating"
        "$mod, P, pseudo"
        "$mod, J, togglesplit"

        # Walker launcher
        "$mod CTRL, space, exec, walker" # Walker launcher (Ctrl+Super+Space)
        "$mod SHIFT, R, exec, pkill quickshell; quickshell &" # Reload Quickshell bar
        # "$mod SHIFT, R, exec, pkill waybar; waybar &" # Reload Waybar (alternative)
        "$mod, left, movefocus, l"
        "$mod, right, movefocus, r"
        "$mod, up, movefocus, u"
        "$mod, down, movefocus, d"
        # Focus prev/next monitor (bracket keys)
        "$mod, bracketleft, focusmonitor, -1"
        "$mod, bracketright, focusmonitor, +1"
        # Workspaces: 1–5 (AZERTY: & é " ' ( = 1 2 3 4 5)
        "$mod, ampersand, workspace, 1"
        "$mod, eacute, workspace, 2"
        "$mod, quotedbl, workspace, 3"
        "$mod, apostrophe, workspace, 4"
        "$mod, parenleft, workspace, 5"
        # Workspace 0 sur DP-3 (touche ² sur AZERTY)
        "$mod, twosuperior, workspace, 9"

        # Move window to workspace 1–5
        "$mod SHIFT, ampersand, movetoworkspace, 1"
        "$mod SHIFT, eacute, movetoworkspace, 2"
        "$mod SHIFT, quotedbl, movetoworkspace, 3"
        "$mod SHIFT, apostrophe, movetoworkspace, 4"
        "$mod SHIFT, parenleft, movetoworkspace, 5"
        # Déplacer fenêtre vers workspace 0 (DP-3)
        "$mod SHIFT, twosuperior, movetoworkspace, 9"

        # Workspace spécial Gemini (Super+G) – s'affiche en overlay
        "$mod, G, togglespecialworkspace, gemini"
      ];

      bindm = [
        "$mod, mouse:272, movewindow"
        "$mod, mouse:273, resizewindow"
      ];

      # Lid switch: when lid closes, move workspaces to HDMI then disable eDP (avoids workspaces stuck on disabled monitor).
      # Only disable eDP if HDMI-A-1 is present, so laptop-only use is unchanged.
      bindl = [
        ", switch:on:Lid Switch, exec, ${hyprClosedLidLayout} --force"
        ", switch:off:Lid Switch, exec, hyprctl keyword monitor 'eDP-1,preferred,auto-left,1.33'"
      ];

      # Window rules: float file pickers and small dialog windows (new 0.53+ syntax)
      windowrule = [
        # File chooser dialogs (Open/Save/Upload)
        "match:title ^(Open File)(.*), float on"
        "match:title ^(Select a File)(.*), float on"
        "match:title ^(Choose Files)(.*), float on"
        "match:title ^(Save File)(.*), float on"
        "match:title ^(Save As)(.*), float on"
        "match:title ^(Upload)(.*), float on"
        "match:title ^(.*File Upload.*), float on"

        # XDG desktop portal file chooser
        "match:class ^(xdg-desktop-portal-gtk)$, float on"
        "match:class ^(xdg-desktop-portal)$, float on"
        "match:class ^(org.freedesktop.impl.portal.desktop.gtk)$, float on"

        # Generic dialog windows
        "match:title ^(.*)(Open|Save|Select|Choose|Upload|Download)(.*), float on"
        # Dolphin file manager
        "match:class ^(org.kde.dolphin)$, float on"
        "match:class ^(org.kde.dolphin)$, size 600 400"
        "match:class ^(org.kde.dolphin)$, center 1"

        "match:class ^(file_progress)$, float on"
        "match:class ^(confirm)$, float on"
        "match:class ^(dialog)$, float on"
        "match:class ^(download)$, float on"
        "match:class ^(notification)$, float on"
        "match:class ^(error)$, float on"
        "match:class ^(splash)$, float on"
        "match:class ^(toolbar)$, float on"
      ];
    };
  };

}
