# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# NOTE: This file is a template for the next install (impermanence + btrfs,
# BIOS/GRUB layout with /boot as a btrfs subvolume).
# UUIDs must be replaced with the values generated by `nixos-generate-config`
# after the new install.
{
  config,
  lib,
  modulesPath,
  ...
}:

let
  btrfsUuid = "REPLACE-WITH-BTRFS-UUID-AT-INSTALL";
  btrfsDevice = "/dev/disk/by-uuid/${btrfsUuid}";
  # No "ssd" flag: kafka is likely on a spinning disk; let btrfs auto-detect.
  btrfsOptions = [
    "compress=zstd:3"
    "noatime"
    "space_cache=v2"
  ];
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "ohci_pci"
    "ehci_pci"
    "pata_atiixp"
    "usbhid"
    "floppy"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = btrfsDevice;
    fsType = "btrfs";
    options = [ "subvol=@" ] ++ btrfsOptions;
  };

  fileSystems."/nix" = {
    device = btrfsDevice;
    fsType = "btrfs";
    options = [ "subvol=@nix" ] ++ btrfsOptions;
  };

  fileSystems."/persist" = {
    device = btrfsDevice;
    fsType = "btrfs";
    options = [ "subvol=@persist" ] ++ btrfsOptions;
    neededForBoot = true;
  };

  # GRUB BIOS reads /boot from btrfs subvolume @boot.
  # @boot is NOT wiped at boot (only @ is), so kernels survive reboots.
  fileSystems."/boot" = {
    device = btrfsDevice;
    fsType = "btrfs";
    options = [ "subvol=@boot" ] ++ btrfsOptions;
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
