# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# NOTE: This file is a template for the next install (impermanence + btrfs + LUKS).
# UUIDs must be replaced with the values generated by `nixos-generate-config`
# after the new install.
{
  config,
  lib,
  modulesPath,
  ...
}:

let
  # UUID of the raw LUKS partition (blkid: the partition containing the LUKS header)
  luksUuid = "REPLACE-WITH-LUKS-PARTITION-UUID-AT-INSTALL";
  # Opened LUKS mapper device — btrfs lives inside this
  btrfsDevice = "/dev/mapper/cryptroot";
  btrfsOptions = [
    "compress=zstd:3"
    "noatime"
    "space_cache=v2"
    "discard=async"
    "ssd"
  ];
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
  ];
  boot.initrd.kernelModules = [ "dm-crypt" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # LUKS encryption — passphrase prompted at boot
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/${luksUuid}";
    allowDiscards = true; # pass TRIM through to the SSD
  };

  fileSystems."/" = {
    device = btrfsDevice;
    fsType = "btrfs";
    options = [ "subvol=@" ] ++ btrfsOptions;
  };

  fileSystems."/nix" = {
    device = btrfsDevice;
    fsType = "btrfs";
    options = [ "subvol=@nix" ] ++ btrfsOptions;
  };

  fileSystems."/persist" = {
    device = btrfsDevice;
    fsType = "btrfs";
    options = [ "subvol=@persist" ] ++ btrfsOptions;
    neededForBoot = true;
  };

  # ESP — unencrypted (required for UEFI bootloader)
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-ESP-UUID-AT-INSTALL";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
